# Generated by Django 4.2.5 on 2023-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Species',
            field=models.CharField(default='Uknown', max_length=255),
        ),
    ]
