# Generated by Django 4.2.5 on 2023-09-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Species',
            new_name='species',
        ),
    ]
