# Generated by Django 4.2.5 on 2023-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_species_item_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='causeOfDeath',
            field=models.CharField(default='Uknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='spiritStatus',
            field=models.CharField(default='Uknown', max_length=255),
        ),
    ]
